title: Laura Bayona-Roman # your name (Advanced GIS Portfolio) here
logo: "images/IMG_6472.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Currently, I'm a Master's student in the Applied Sociology Program at the University of Maryland, Baltimore County.
  <br><br>
  My research interests include social movements, trust in government, elections, and what attracts people to certain political ideologies and figures.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
